#ifndef FIELDOFVIEWSECTORS_H
#define FIELDOFVIEWSECTORS_H

enum class FieldOfViewSectors {
    UPPER_LEFT, UPPER_CENTER, UPPER_RIGHT,
    CENTER_LEFT, CENTER_CENTER, CENTER_RIGHT,
    BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
};

#endif